version: '2'
services:
  my-postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
    
  trunk-image:
    image: trunk-image
    build: ./trunk.cocoapods.org
    container_name: trunk-image
    command: bash -c "cd Humus && rake db:bootstrap && cd .. && TRUNK_APP_ADMIN_PASSWORD=admin GH_TOKEN=6aa453351cedb84f87120c6919a70b23c61cc086 rake serve"
    volumes:
      - ./trunk.cocoapods.org:/trunk
    ports:
      - "4567:4567"
    depends_on:
      - my-postgres
    links:
      - my-postgres

  search-image:
    image: search-image
    build: ./search-api
    container_name: search-image
    command: bash -c "rake serve"
    volumes:
     - ./search-api:/search
    ports:
      - "8888:8888"
    depends_on:
      - my-postgres
    links:
      - my-postgres
volumes:
  db-data:
