FROM ubuntu:14.04

# Update Apt
RUN apt-get -y update
RUN apt-get -y install curl git-core python-software-properties

# install essentials
RUN apt-get -y install build-essential
RUN apt-get install -y -q git
RUN apt-get install -y libssl-dev

# Install rbenv
RUN git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
RUN echo '# rbenv setup' > /etc/profile.d/rbenv.sh
RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> /etc/profile.d/rbenv.sh
RUN echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> /etc/profile.d/rbenv.sh
RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
RUN chmod +x /etc/profile.d/rbenv.sh

# install ruby-build
RUN mkdir /usr/local/rbenv/plugins
RUN git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build

ENV RBENV_ROOT /usr/local/rbenv

ENV PATH $RBENV_ROOT/bin:$RBENV_ROOT/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Install ruby 2.1.3
RUN rbenv install 2.1.3
RUN rbenv global 2.1.3
RUN ruby -v

# Install bundler
RUN gem install bundler

# Install Postgres 9.3
RUN sh -c "echo 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
RUN wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
RUN apt-get update
RUN apt-get install postgresql-common
RUN apt-get install postgresql-9.3 libpq-dev

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
 
COPY . /usr/src/app
 
#!/bin/bash
RUN bundle install

EXPOSE 4567


# Copy the main application.
COPY . ./

# Expose port 4567 to the Docker host, so we can access it 
# from the outside.
EXPOSE 4567